### ISSUE TITLE
Mac issues

### ISSUE THREAD

**Issue by RageEZ** [scalic/scalic-selfbot#5]
Doesn't seem to be working on Mac, it says this for me

sh: pip: command not found
Traceback (most recent call last):
  File "/Users/Luke/Desktop/scalic-selfbot-main/scalic.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Luke/Desktop/scalic-selfbot-main/scalic.py", line 15, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by kieronia** [comment]
pip install requests

**Comment by RageEZ** [comment]
now it says ImportError: No module named typing

**Comment by aqce** [comment]
Let's be smart now, type pip install typing

Then so on and so forth.
